apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshot
metadata:
  name: example-snapshot
spec:
  volumeSnapshotClassName: example-snapclass
  source:
    persistentVolumeClaimName: example-vanilla-block-pvc