apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: example-restored-pvc-2g
spec:
  storageClassName: example-vanilla-block-sc
  dataSource:
    name: example-snapshot
    kind: VolumeSnapshot
    apiGroup: snapshot.storage.k8s.io
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi